import React from 'react';
export const metadata = {
  title: "social page",
  description: "Generated by create next app",
};

const EmailPage = () => {
  return (
    <div>
      <h3> You can email me in my email box, </h3>
    </div>
  );
};

export default EmailPage;