import Counter from '@/Components/Counter/Counter';
import React from 'react';

export const metadata = {
  title: "skill page",
  description: "Generated by create next app",
};

const SkillsPage = () => {
  return (
    <div>
      <h2>Lets talk about my skills</h2>
      <Counter></Counter>
    </div>
  );
};

export default SkillsPage;